return {
  'yousefhadder/markdown-plus.nvim',
  ft = 'markdown',
  keys = {
    { '<CR>', '<Plug>(MarkdownPlusListEnter)', mode = 'i', ft = 'markdown', desc = 'Markdown list enter' },
    { '<A-CR>', '<Plug>(MarkdownPlusListShiftEnter)', mode = 'i', ft = 'markdown', desc = 'Markdown list continue content' },
    { '<Tab>', '<Plug>(MarkdownPlusListIndent)', mode = 'i', ft = 'markdown', desc = 'Markdown list indent' },
    { '<S-Tab>', '<Plug>(MarkdownPlusListOutdent)', mode = 'i', ft = 'markdown', desc = 'Markdown list outdent' },
    { '<BS>', '<Plug>(MarkdownPlusListBackspace)', mode = 'i', ft = 'markdown', desc = 'Markdown list smart backspace' },
    { 'o', '<Plug>(MarkdownPlusNewListItemBelow)', mode = 'n', ft = 'markdown', desc = 'Markdown new list item below' },
    { 'O', '<Plug>(MarkdownPlusNewListItemAbove)', mode = 'n', ft = 'markdown', desc = 'Markdown new list item above' },
    { '<localleader>mx', '<Plug>(MarkdownPlusToggleCheckbox)', mode = 'n', ft = 'markdown', desc = 'Markdown toggle checkbox' },
    { '<localleader>mx', '<Plug>(MarkdownPlusToggleCheckbox)', mode = 'x', ft = 'markdown', desc = 'Markdown toggle checkbox' },
    { '<C-t>', '<Plug>(MarkdownPlusToggleCheckbox)', mode = 'i', ft = 'markdown', desc = 'Markdown toggle checkbox' },
    { '<localleader>mr', '<Plug>(MarkdownPlusRenumberLists)', mode = 'n', ft = 'markdown', desc = 'Markdown renumber lists' },
    { '<localleader>tc', '<Plug>(MarkdownPlusTableCreate)', mode = 'n', ft = 'markdown', desc = 'Markdown table create' },
    { '<localleader>tf', '<Plug>(MarkdownPlusTableFormat)', mode = 'n', ft = 'markdown', desc = 'Markdown table format' },
    { '<localleader>tn', '<Plug>(MarkdownPlusTableNormalize)', mode = 'n', ft = 'markdown', desc = 'Markdown table normalize' },
    { '<localleader>tir', '<Plug>(MarkdownPlusTableInsertRowBelow)', mode = 'n', ft = 'markdown', desc = 'Markdown table insert row below' },
    { '<localleader>tiR', '<Plug>(MarkdownPlusTableInsertRowAbove)', mode = 'n', ft = 'markdown', desc = 'Markdown table insert row above' },
    { '<localleader>tdr', '<Plug>(MarkdownPlusTableDeleteRow)', mode = 'n', ft = 'markdown', desc = 'Markdown table delete row' },
    { '<localleader>tyr', '<Plug>(MarkdownPlusTableDuplicateRow)', mode = 'n', ft = 'markdown', desc = 'Markdown table duplicate row' },
    { '<localleader>tic', '<Plug>(MarkdownPlusTableInsertColumnRight)', mode = 'n', ft = 'markdown', desc = 'Markdown table insert column right' },
    { '<localleader>tiC', '<Plug>(MarkdownPlusTableInsertColumnLeft)', mode = 'n', ft = 'markdown', desc = 'Markdown table insert column left' },
    { '<localleader>tdc', '<Plug>(MarkdownPlusTableDeleteColumn)', mode = 'n', ft = 'markdown', desc = 'Markdown table delete column' },
    { '<localleader>tyc', '<Plug>(MarkdownPlusTableDuplicateColumn)', mode = 'n', ft = 'markdown', desc = 'Markdown table duplicate column' },
    { '<localleader>ta', '<Plug>(MarkdownPlusTableToggleCellAlignment)', mode = 'n', ft = 'markdown', desc = 'Markdown table toggle alignment' },
    { '<localleader>tx', '<Plug>(MarkdownPlusTableClearCell)', mode = 'n', ft = 'markdown', desc = 'Markdown table clear cell' },
    { '<localleader>tmj', '<Plug>(MarkdownPlusTableMoveRowDown)', mode = 'n', ft = 'markdown', desc = 'Markdown table move row down' },
    { '<localleader>tmk', '<Plug>(MarkdownPlusTableMoveRowUp)', mode = 'n', ft = 'markdown', desc = 'Markdown table move row up' },
    { '<localleader>tmh', '<Plug>(MarkdownPlusTableMoveColumnLeft)', mode = 'n', ft = 'markdown', desc = 'Markdown table move column left' },
    { '<localleader>tml', '<Plug>(MarkdownPlusTableMoveColumnRight)', mode = 'n', ft = 'markdown', desc = 'Markdown table move column right' },
    { '<localleader>tt', '<Plug>(MarkdownPlusTableTranspose)', mode = 'n', ft = 'markdown', desc = 'Markdown table transpose' },
    { '<localleader>tsa', '<Plug>(MarkdownPlusTableSortAscending)', mode = 'n', ft = 'markdown', desc = 'Markdown table sort ascending' },
    { '<localleader>tsd', '<Plug>(MarkdownPlusTableSortDescending)', mode = 'n', ft = 'markdown', desc = 'Markdown table sort descending' },
    { '<localleader>tvx', '<Plug>(MarkdownPlusTableToCSV)', mode = 'n', ft = 'markdown', desc = 'Markdown table to CSV' },
    { '<localleader>tvi', '<Plug>(MarkdownPlusTableFromCSV)', mode = 'n', ft = 'markdown', desc = 'Markdown CSV to table' },
    { '<A-h>', '<Plug>(MarkdownPlusTableNavLeft)', mode = 'i', ft = 'markdown', desc = 'Markdown table nav left' },
    { '<A-l>', '<Plug>(MarkdownPlusTableNavRight)', mode = 'i', ft = 'markdown', desc = 'Markdown table nav right' },
    { '<A-k>', '<Plug>(MarkdownPlusTableNavUp)', mode = 'i', ft = 'markdown', desc = 'Markdown table nav up' },
    { '<A-j>', '<Plug>(MarkdownPlusTableNavDown)', mode = 'i', ft = 'markdown', desc = 'Markdown table nav down' },
  },
  opts = {
    keymaps = {
      enabled = false,
    },
  },
}
